coisa = input('Digite algo: ')

print(f'Tipo primitivo {type(coisa)}')
print(f'É  um caracter alphanumérico? {coisa.isalnum()}')
print(f'É um numérico? {coisa.isnumeric()}')
print(f'É uma letra? {coisa.isalpha()}')
print(f'É um número decimal? {coisa.isdecimal()}')
print(f'É um digito? {coisa.isdigit()}')
print(f'É somente espaço? {coisa.isspace()}')
print(f'É identificado? {coisa.isidentifier()}')
print(f'É do padrão ascii? {coisa.isascii()}')
print(f'Está em letras maiúsculas? {coisa.isupper()}')
print(f'Está em letras minúsculas? {coisa.islower()}')
print(f'É um título? {coisa.istitle()}')